awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=28
awesome_regular: &awesome_regular Font Awesome 5 Free:style=regular:pixelsize=28
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=28
iosevka: &iosevka Iosevka:pixelsize=26

std_underline: &std_underline { underline: { size: 2, color: ff0000ff } }

color_bg: &color_bg 121517ff
color_select: &color_select 828e98ff
color_red: &color_red d16a61ff
color_green: &color_green a3bd61ff
color_yellow: &color_yellow cca161ff
color_blue: &color_blue 60a6d2ff
color_magenta: &color_magenta ca88d3ff
color_cyan: &color_cyan 55b499ff
color_white: &color_white bfc6cbff

bar:
  height: 56
  location: top
  spacing: 10
  margin: 24 # padding 6px * 2 * 2 (scale)
  font: *iosevka # Default font
  foreground: DDE1E4ff
  background: *color_bg

  left:
    - river:
        anchors:
          - base: &river_base
              margin: 10
              tag: id
              default: { string: { text: "{id}", font: *iosevka } }
              values:
                1: { string: { text: I } }
                2: { string: { text: II } }
                3: { string: { text: III } }
                4: { string: { text: IV } }
                5: { string: { text: V } }
                6: { string: { text: VI } }
                7: { string: { text: VII } }
                8: { string: { text: VIII } }
                9: { string: { text: IX } }
        content:
          map:
            tag: state
            values:
              focused:
                map:
                  <<: *river_base
                  foreground: *color_bg
                  deco: { stack: [background: { color: *color_yellow }] }
              invisible:
                map:
                  tag: occupied
                  values:
                    false: { empty: {} }
                    true:
                      { map: { <<: *river_base, foreground: *color_select } }
  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        anchors:
          list: &artist_album_title
            spacing: 0
            items:
              - map:
                  tag: state
                  values:
                    playing: { string: { text: "{artist}" } }
                    paused:
                      { string: { text: "{artist}", foreground: ffffff66 } }
              - string: { text: " | ", foreground: ffffff66 }
              - map:
                  tag: state
                  values:
                    playing: { string: { text: "{album}" } }
                    paused:
                      { string: { text: "{album}", foreground: ffffff66 } }
              - string: { text: " | ", foreground: ffffff66 }
              - map:
                  tag: state
                  values:
                    playing:
                      { string: { text: "{title}", foreground: ffa0a0ff } }
                    paused:
                      { string: { text: "{title}", foreground: ffffff66 } }
        content:
          map:
            margin: 10
            tag: state
            values:
              offline: { string: { text: offline, foreground: ff0000ff } }
              stopped: { string: { text: stopped } }
              paused: { list: *artist_album_title }
              playing: { list: *artist_album_title }

  right:
    - removables:
        anchors:
          drive: &drive { text: , font: *awesome }
          optical: &optical { text: , font: *awesome }
        spacing: 5
        content:
          map:
            tag: mounted
            values:
              false:
                map:
                  tag: optical
                  on-click: udisksctl mount -b {device}
                  values:
                    false: [{ string: *drive }, { string: { text: "{label}" } }]
                    true:
                      [{ string: *optical }, { string: { text: "{label}" } }]
              true:
                map:
                  tag: optical
                  on-click: udisksctl unmount -b {device}
                  values:
                    false:
                      - string: { <<: *drive, deco: *std_underline }
                      - string: { text: "{label}" }
                    true:
                      - string: { <<: *optical, deco: *std_underline }
                      - string: { text: "{label}" }
    - network:
        name: enp1s0
        content:
          map:
            tag: carrier
            values:
              false: { empty: {} }
              true:
                map:
                  tag: state
                  default:
                    {
                      string: { text: , font: *awesome, foreground: ffffff66 },
                    }
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: { string: { text: , font: *awesome } }
                        values:
                          "":
                            {
                              string:
                                {
                                  text: ,
                                  font: *awesome,
                                  foreground: ffffff66,
                                },
                            }
    - network:
        name: wlp3s0
        content:
          map:
            tag: state
            default:
              { string: { text: , font: *awesome, foreground: ffffff66 } }
            values:
              down:
                { string: { text: , font: *awesome, foreground: ff0000ff } }
              up:
                map:
                  tag: ipv4
                  default:
                    - string: { text: , font: *awesome }
                  values:
                    "":
                      - string:
                          { text: , font: *awesome, foreground: ffffff66 }
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            tag: online
            values:
              false:
                { string: { text: , font: *awesome, foreground: ff0000ff } }
              true:
                map:
                  on-click: /bin/sh -c "amixer -q sset Speaker unmute;amixer -q sset Headphone unmute;amixer -q sset Master toggle"
                  tag: muted
                  values:
                    true:
                      {
                        string:
                          { text: , font: *awesome, foreground: ffffff66 },
                      }
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string: { text: , font: *awesome }
                          - string: { text: , font: *awesome }
                          - string: { text: , font: *awesome }
                          - string: { text: , font: *awesome }
                          - string: { text: , font: *awesome }
    - battery:
        name: BAT0
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string:
                          { text: , foreground: *color_red, font: *awesome }
                      - string:
                          { text: , foreground: ffa600ff, font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string: { text: , font: *awesome }
                      - string:
                          { text: , foreground: *color_green, font: *awesome }
                - string: { text: "{capacity}%" }
              charging:
                - string: { text: , foreground: *color_green, font: *awesome }
                - string: { text: "{capacity}%" }
              full:
                - string: { text: , foreground: *color_green, font: *awesome }
                - string: { text: "{capacity}%" }
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string:
                          { text:  , foreground: ff0000ff, font: *awesome }
                      - string:
                          { text:  , foreground: ffa600ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                      - string:
                          { text:  , foreground: 00ff00ff, font: *awesome }
                - string: { text: "{capacity}%" }
    - clock:
        time-format: "%H:%M"
        content:
          - string: { text: , font: *awesome, right-margin: 10 }
          - string: { text: "{date}", right-margin: 10 }
          - string: { text: , font: *awesome }
          - string: { text: "{time}" }
    - label:
        content:
          string:
            on-click: loginctl poweroff
            text: 
            font: *awesome
